### ISSUE TITLE
Problem with some sequences uploaded in the portal

### ISSUE THREAD

**Issue by think-o** [animesh-workplace/sars-frontend#11]
Hi! So I will have to make some changes with the IDs of the data uploaded to the portal. Can I get your email ID ? I want to contact you in person. Could not find any contact information in the portal and over here. Thanks!

**Comment by animesh-workplace** [comment]
Please send us your email and we will contact you adn address the issue

**Comment by think-o** [comment]
Hi!

This is my email ID ***@***.***). Please get back to me.

Thank you,
Malini,

**Comment by animesh-workplace** [comment]
Unable to see your mail id 
![image](https://user-images.githubusercontent.com/55780901/156737429-253e37e4-6ce7-413d-bbf0-cc0aef3b15a8.png)

**Comment by think-o** [comment]
> Unable to see your mail id ![image](https://user-images.githubusercontent.com/55780901/156737429-253e37e4-6ce7-413d-bbf0-cc0aef3b15a8.png)

It's nkmalini97@gmail.com
