### ISSUE TITLE
Getting data and metadata

### ISSUE THREAD

**Issue by saketkc** [animesh-workplace/sars-frontend#3]
Hi,

Thanks for creating and maintaining this great interface! Is it possible to include a flatfile(csv/tsv) dump of all the sequences being deposited
which at the bare minimum as the following fields:

```
1. ID
2. Pangolin lineage
3. Age
4. Gender
5. Variant
3. State
4. District
5. City/Location
6. Submitting lab
7. Originating Lab
8. Collection Date
9. Submission Date
10. Sequencing Platform
11. QC metrics for fasta sequences
12. Any other clinically relevant metadata (this in my opinion currently does not exist, but would be extremely useful)
```

Thanks!
Saket

**Comment by animesh-workplace** [comment]
Most of the information requested is also available on GISAID, but if you still need access to this data you can apply to INSACOG consortium @saketkc

**Comment by saketkc** [comment]
Thanks, I am aware and have been using data from GISAID. Can you help me with the link for raising a request for data access to INSACOG? My understanding is that only participating laboratories only have access - are individuals allowed to access the data through some sort of membership?

**Comment by animesh-workplace** [comment]
This resource from [DBT INSACOG website](https://dbtindia.gov.in/insacog) might be helpful. Extremely sorry for the delay in response

![image](https://user-images.githubusercontent.com/55780901/156713755-a7c74c1d-2670-4b00-a2c0-55d2d69de64b.png)

**Comment by saketkc** [comment]
No worries, thanks! I understand.
